### ISSUE TITLE
Support custom includePaths

### ISSUE THREAD

**Issue by wkillerud** [wkillerud/some-sass#41] opened 2023-03-12 17:07 UTC
Using SCSS from `node_modules` is well supported, but if the project relies on other custom `includePaths` (see #36), things don't work that well.

- The link parser likely assumes things are in `node_modules` when they're not.
- Since the parser is confused, most functionality is likely either not working or working with incomplete information.

More research is needed. I think we'll at least need:

- A new setting to allow configuring custom `includePaths` (list of paths).
- A (local) patch of `vscode-css-languageservice`, or some other way to have [findDocumentLinks](https://github.com/wkillerud/vscode-scss/blob/d58245f26c3ddefab6922c7bd6c8ebcc4037d68a/server/src/parser/parser.ts#L57) understand `includePaths`.
- Once the parser understands `includePaths`, test all features with source code from `includePaths`.
- A `documentLinkProvider` capability for the server, to fix Ctrl/Cmd + click on `@use/@forward/@import` in `includePaths`.

**Comment by Deemoguse** [comment] 2023-12-07 09:26
The problem is, how exactly to resolve the path to the module specified using the alias?

**Comment by Deemoguse** [comment] 2023-12-13 08:54
I can see that. I was able to make it work for auto-completion. The solution was the introduction of the `ensureScssAliases` function, which resolves aliases and generates a new uri for `target`:

```ts
export function ensureScssAliases(
	target: string,
	aliases: Record<string, string>,
): string {
	const aliasEntries = Object.entries(aliases);

	for (let i = 0; i < aliasEntries.length; i++) {
		const [key, path] = aliasEntries[i];

		// Skip if the key or path is empties:
		if (!key || !path) continue;

		// Check types:
		if (typeof key !== "string")
			throw new TypeError("The alias name must be a string");
		if (typeof path !== "string")
			throw new TypeError("The alias path must be a string");

		const fixedKey = key.replace(/\/$/, "");
		const encodeKey = encodeURIComponent(fixedKey);

		if (target.includes(encodeKey)) {
			const splitter = new RegExp(`(?=${encodeKey})`);
			const pathFromWorkspace = target.split(splitter)[0];
			const resolvedAlias = pathFromWorkspace.replace(encodeKey, aliases[key]);

			return URI.file(resolvedAlias).toString();
		}
	}

	return target;
}
```

For the rest of the server functions, aliases are still a problem. I don't know this project well enough, so I'm going to need some help to fully solve this problem.

**Comment by wkillerud** [comment] 2023-12-13 18:58
Nice, thanks for looking into this.

Is this function added to `parser.ts`, for instance here? https://github.com/wkillerud/vscode-scss/blob/58227ce79999a2d9e046a9db351752804d655bc5/server/src/parser/parser.ts#L91C18-L91C37

Or did you try it locally somewhere in [`completion.ts`](https://github.com/wkillerud/vscode-scss/blob/main/server/src/features/completion/completion.ts)? If so, the parser is the more central location that could help cover the other features.

Feel free to open a draft pull request (or regular, either is fine). It's easier to help when I can see the code in context 🙌 

For reference, the [scanner](https://github.com/wkillerud/vscode-scss/blob/main/server/src/scanner.ts) is what gets [called on startup](https://github.com/wkillerud/vscode-scss/blob/58227ce79999a2d9e046a9db351752804d655bc5/server/src/server.ts#L156) and when a [file is changed](https://github.com/wkillerud/vscode-scss/blob/58227ce79999a2d9e046a9db351752804d655bc5/server/src/server.ts#L168). The scanner again calls [the parser](https://github.com/wkillerud/vscode-scss/blob/58227ce79999a2d9e046a9db351752804d655bc5/server/src/scanner.ts#L73C17-L73C17). The parsed files are [stored in memory](https://github.com/wkillerud/vscode-scss/blob/58227ce79999a2d9e046a9db351752804d655bc5/server/src/scanner.ts#L77), and that in-memory storage is what gets checked in all the features (completions, hover info, etc). So any work done in the parser/scanner part of the project benefits all the features.

**Comment by Deemoguse** [comment] 2023-12-18 11:41
I will do some research on this issue and try to solve it. I will immediately create a pr if I have any difficulties :)

**Comment by Fernker** [comment] 2024-02-22 16:58
I'm not sure if this is helpful but we've been working on a Scss module with Angular that needs both VSCode and WebStorm support.  In WebStorm it was complaining about our `@use 'shorthand';` approach even with includePaths.  We had to add an alias to the webpack.config file as pointed out to here:  https://stackoverflow.com/a/46303960

For the `includePaths` we point it to the directory where the Scss module starting file is.  But for the webpack.config alias entry we point it to the actual starting file.

Not sure if that helps but it's been on my mind as we've had this type of issue with both VSCode and WebStorm in the past but we were finally able to get it resolved with WebStorm.

**Comment by niksy** [comment] 2024-07-30 14:29
Any progress on this feature? It’s too bad that Sass doesn’t expose this as sam kind of API, but can this be simplified to list of mapped paths and module path which are sent to JS URL resolver, checking if that path exists (in parallel with e.g. `Promise.allSettled`) and using first result that resolved successfully?

**Closed** 2024-07-30 17:33 UTC

**Comment by wkillerud** [comment] 2024-07-30 17:42
Luckily some earlier refactoring made this feasible to add. Try it out in version [3.2.0](https://github.com/wkillerud/some-sass/releases/tag/some-sass%403.2.0) and let me know if there are any issues.

**Comment by niksy** [comment] 2024-07-31 08:03
This is it, thanks!
